version: '3'
services:
  ssh-service:
    build: .
    ports:
      - "2222:22"
    volumes:
      - ./authorized_keys:/root/.ssh/authorized_keys
      - /var/run/docker.sock:/var/run/docker.sock  # Docker socket
